gupao:
  sentinel:
    host: 47.93.233.188
    port: 9090
  redis:
    host: 47.93.233.188
    port: 6379
  mysql:
    host: 47.93.233.188
    port: 3306
  kafka:
    host: 192.168.159.181
    port: 9092
server:
  port: 18011
#暂时暴露全部端点，生产环境应该选择一部分暴露
management.endpoints.web.exposure.include: '*'
spring:
  cloud:
#============== sentinel ===================
    #限流
    sentinel:
      #sentinel控制台地址
      transport:
        dashboard: ${gupao.sentinel.host}:${gupao.sentinel.port}
      #取消Sentinel控制台懒加载
      eager: true
      datasource:
        #自己定义的datasource名称
        flow:
          #使用nacos作为数据源
          nacos:
            server-addr: ${gupao.nacos.host}:${gupao.nacos.port}
            dataId: ${spring.application.name}-flow-rules
            namespace: ${gupao.nacos.namespace}
            groupId: DEFAULT_GROUP
            rule-type: flow
#============== redis ===================
  redis:
      host: ${gupao.redis.host}
      port: ${gupao.redis.port}
#      password: mylava
      database: 0
#============== mysql ===================
  datasource:
    # 配置数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${gupao.mysql.host}:${gupao.mysql.port}/gupao_backend?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
    username: root
    password: 123456
#============== kafka ===================
  #指定kafka server的地址，集群配多个，中间，逗号隔开
  kafka:
    bootstrap-servers: ${gupao.kafka.host}:${gupao.kafka.port}
    #---------- producer ----------
    producer:
      #重发
      retries: 0
      #缓存消息发送数量阈值
      batch-size: 16384
      #缓存消息发送内存阈值
      buffer-memory: 33554432
      # 只需要leader节点返回ack
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    #---------- consumer ----------
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#============== mybatis-plus ===================
mybatis-plus:
  global-config:
    db-config:
      #ID类型为自增
      id-type: auto
      #字段非空检查
      field-strategy: not_empty
      table-underline: true
#      db-type: mysql
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:/mapper/*.xml,classpath:/mapper/AreaMapper.xml,classpath:/mapper/DictMapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.gupao.edu.account.entity   #自己的实体类地址
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#============== logging ===================
logging:
  level:
    com.alibaba.nacos: error
    org.springframework.cloud.sleuth: debug

app_id_qq: 101485748
app_key_qq: c8743f061a535d8595ef8b61fb6ef571
redirect_url_qq: http://47.93.233.188:20001/qqcallback
scope_qq: get_user_info
getUserInfoURL_qq: https://graph.qq.com/user/get_user_info
accessTokenURL_qq: https://graph.qq.com/oauth2.0/token
getOpenIDURL_qq: https://graph.qq.com/oauth2.0/me
authorizeURL_qq: https://graph.qq.com/oauth2.0/authorize


app_id_wechat: wx2b6ff83da441f5fe
app_key_wechat: 92d4672f564f5e9eca01c5cb9f079f54
redirect_url_wechat: https://gper.club/wechatcallback
authorizationURL_wechat: https://open.weixin.qq.com/connect/qrconnect
getUserInfoURL_wechat: https://api.weixin.qq.com/sns/userinfo
accessTokenURL_wechat: https://api.weixin.qq.com/sns/oauth2/access_token

dingxiang_app_id: f5ce2dba91ccad9eabd1ac8c8373dfa1
dingxiang_app_key: 96aa77e2ab1fef7244192ae0bc7c01ab

user:
  #密码加密盐值
  password:
    salt: 123456
   #登录jwt key
  jwt:
    secret: ^LAu3iJkxoB*kypOA5MRK7NRHk7QW4mp

#============== 云片配置 ===================
sms_yunpian_tz_apikey: bdd46e7c95fad7dfb71b58a5f0103f3f
sms_yunpian_baseurl: https://sms.yunpian.com
sms_yunpian_version: v2
sms_yunpian_alltpl: tpl/get.json
sms_yunpian_getalltplurl: ${sms_yunpian_baseurl}/${sms_yunpian_version}/${sms_yunpian_alltpl}
message_templateId: 2630458
message_smsUrl: http://47.93.233.188:20009/sms/message/sendtpl
